Repository pusher/git-store, pull requests merged in 2019-08, with the labels that each got.

#22 Makefile should be able to configure
  Makefile
Labels: size/XS

#21 Remove local references from Git repository
  cloner.go
  cloner_test.go
  repo.go
Labels: size/L

#20 Add ability to clone files to the filesystem
  cloner.go
  cloner_test.go
  repo_test.go
  store.go
  store_test.go
Labels: size/L

#23 Fix cleaning of non-master branches
  cloner_test.go
  repo.go
Labels: size/L

#24 Open repository if it has already been cloned
  cloner.go
  cloner_test.go
Labels: size/S
